name: sg
channels:
  - plotly
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.2.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.14.0
  - beautifulsoup4=4.12.2
  - blas=1.1
  - bleach=6.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cffi=1.16.0
  - colorama=0.4.6
  - comm=0.1.4
  - cudatoolkit=11.3.1
  - dataclasses=0.8
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - future=0.18.3
  - fvcore=0.1.5.post20221221
  - giflib=5.2.1
  - icu=73.2
  - importlib-metadata=7.0.0
  - importlib_metadata=7.0.0
  - importlib_resources=6.1.1
  - iopath=0.1.9
  - ipykernel=6.26.0
  - ipython=8.19.0
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.20.0
  - jsonschema-specifications=2023.11.2
  - jsonschema-with-format-nongpl=4.20.0
  - jupyter-lsp=2.2.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.1
  - jupyter_events=0.9.0
  - jupyter_server=2.12.1
  - jupyter_server_terminals=0.5.0
  - jupyterlab=4.0.9
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.2
  - jupyterlab_widgets=3.0.9
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.25
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libuv=1.46.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libzlib=1.2.13
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mistune=3.0.2
  - nbclient=0.8.0
  - nbconvert-core=7.13.1
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nodejs=20.9.0
  - notebook-shim=0.2.3
  - openblas=0.3.25
  - openssl=3.2.0
  - overrides=7.4.0
  - packaging=23.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.1.0
  - plotly=5.18.0
  - plyfile=0.8.1
  - portalocker=2.8.2
  - prometheus_client=0.19.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.7
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.0
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - referencing=0.32.0
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.0
  - rpds-py=0.15.2
  - send2trash=1.8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.44.2
  - stack_data=0.6.2
  - tabulate=0.9.0
  - tenacity=8.2.3
  - termcolor=2.3.0
  - terminado=0.18.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.14.0
  - types-python-dateutil=2.8.19.14
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - uri-template=1.3.0
  - wcwidth=0.2.12
  - webcolors=1.13
  - webencodings=0.5.1
  - wheel=0.42.0
  - widgetsnbextension=4.0.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.5
  - yacs=0.1.8
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - accelerate==0.25.0
      - addict==2.4.0
      - annotated-types==0.6.0
      - ansi2html==1.9.1
      - appdirs==1.4.4
      - av==11.0.0
      - bidict==0.22.1
      - blinker==1.7.0
      - blis==0.7.11
      - build==1.0.3
      - cachetools==5.3.2
      - catalogue==2.0.10
      - certifi==2022.12.7
      - chardet==5.2.0
      - charset-normalizer==2.1.1
      - click==8.1.7
      - cloudpathlib==0.16.0
      - colorlog==6.8.0
      - comet-ml==3.35.5
      - confection==0.1.4
      - configargparse==1.7
      - configobj==5.0.8
      - contourpy==1.2.0
      - cryptography==41.0.7
      - cycler==0.12.1
      - cymem==2.0.8
      - dash==2.14.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dearpygui==1.10.1
      - descartes==1.1.0
      - diff-gaussian-rasterization==0.0.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.15
      - dulwich==0.21.7
      - einops==0.7.0
      - embreex==2.17.7.post4
      - everett==3.1.0
      - face-alignment==1.4.0
      - fastai==2.7.13
      - fastcore==1.5.29
      - fastdownload==0.0.7
      - fastprogress==1.0.3
      - filelock==3.9.0
      - fire==0.5.0
      - flask==3.0.0
      - fonttools==4.47.0
      - fsspec==2023.12.2
      - gdown==4.7.1
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.25.2
      - google-auth-oauthlib==1.2.0
      - grpcio==1.60.0
      - h11==0.14.0
      - h5py==3.10.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.20.1
      - idna==3.4
      - imageio==2.33.1
      - imageio-ffmpeg==0.4.9
      - itsdangerous==2.1.2
      - jaxtyping==0.2.25
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - kornia==0.7.0
      - langcodes==3.3.0
      - lazy-loader==0.3
      - lightglue==0.0
      - lightning-utilities==0.10.0
      - llvmlite==0.41.1
      - lpips==0.1.4
      - lxml==4.9.4
      - mapbox-earcut==1.0.1
      - markdown==3.5.1
      - matplotlib==3.5.3
      - mediapy==1.2.0
      - mpmath==1.3.0
      - msgpack==1.0.7
      - msgpack-numpy==0.4.8
      - murmurhash==1.0.10
      - nbformat==5.7.0
      - nerfacc==0.5.2
      - nerfstudio==0.3.4
      - networkx==3.0
      - ninja==1.11.1.1
      - nodeenv==1.8.0
      - numba==0.58.1
      - numpy==1.24.1
      - nuscenes-devkit==1.1.11
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - open3d==0.17.0
      - opencv-python==4.6.0.66
      - pandas==2.1.4
      - pillow==9.3.0
      - preshed==3.0.9
      - protobuf==3.20.3
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyaudio==0.2.14
      - pycocotools==2.0.7
      - pycollada==0.7.2
      - pycolmap==0.4.0
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pyliblzfse==0.4.1
      - pymcubes==0.1.4
      - pymesh==1.0.2
      - pymeshlab==2023.12
      - pyngrok==7.0.3
      - pyparsing==3.1.1
      - pyproject-hooks==1.0.0
      - pyquaternion==0.9.9
      - pysocks==1.7.1
      - python-box==6.1.0
      - python-engineio==4.8.0
      - python-socketio==5.10.0
      - python-speech-features==0.6
      - pytorch3d==0.7.5
      - rawpy==0.19.0
      - regex==2023.12.25
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - resampy==0.4.2
      - retrying==1.3.4
      - rsa==4.9
      - rtree==1.1.0
      - safetensors==0.4.1
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - semantic-version==2.10.0
      - sentry-sdk==1.39.1
      - setproctitle==1.3.3
      - shapely==1.8.5.post1
      - shtab==1.6.5
      - simple-knn==0.0.0
      - simple-websocket==1.0.0
      - simplejson==3.19.2
      - smart-open==6.4.0
      - smmap==5.0.1
      - soundfile==0.12.1
      - spacy==3.7.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - splines==0.3.0
      - srsly==2.4.8
      - svg-path==6.3
      - sympy==1.12
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - thinc==8.2.2
      - threadpoolctl==3.2.0
      - tifffile==2023.12.9
      - timm==0.6.7
      - tokenizers==0.15.0
      - torch==2.1.2+cu118
      - torch-ema==0.3
      - torch-fidelity==0.3.0
      - torchaudio==2.1.2+cu118
      - torchmetrics==1.2.1
      - torchvision==0.16.2+cu118
      - transformers==4.36.2
      - trimesh==4.0.8
      - triton==2.1.0
      - typeguard==2.13.3
      - typer==0.9.0
      - tyro==0.6.2
      - tzdata==2023.3
      - urllib3==1.26.13
      - viser==0.1.3
      - wandb==0.16.1
      - wasabi==1.1.2
      - weasel==0.3.4
      - websocket-client==1.3.3
      - websockets==12.0
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - wsproto==1.2.0
      - wurlitzer==3.0.3
      - xatlas==0.0.8
      - xxhash==3.4.1
      - yourdfpy==0.0.53
